#pragma once

/** @file
    @brief The reflection-generated Python exception hierarchy for wowlib failures.

    Every fallible wowlib call returns a @c Result<T> (std::expected). The caster
    in @c result_casters.hpp unwraps success and throws @c wowlib::ResultError on
    failure; the translator installed here maps that carrier onto a Python
    exception class chosen by the failure's @c ErrorCode. The class tree is
    generated by reflecting over @c ErrorCode — a base @c wowlib.Error plus one
    subclass per enumerator — so new error codes grow new exception classes with no
    hand-maintained table. */

#include <nanobind/nanobind.h>

namespace wowlib_py
{
  namespace nb = nanobind;

  /** @brief Build the exception hierarchy and install the Result-error translator.

      Creates @c wowlib.Error (the common base) and one subclass per @c ErrorCode
      enumerator on @p module, some also deriving from a curated Python builtin
      (e.g. @c FileNotFound → @c FileNotFoundError) so idiomatic handlers work, then
      registers the @c wowlib::ResultError → exception translator.

      Call once from the module body, after welder's walk has populated @p module.

      @param module the extension module being initialized. */
  void registerErrors(nb::module_& module);
}
